language: cpp
os:
  - linux
  - windows

jobs:
  include:
    - name: "Linux Build"
      os: linux
      dist: focal
      before_install:
        - sudo apt-get update
        - sudo apt-get install -y cmake
      script:
        - cmake -S . -B build
        - cmake --build build -j 4

    - name: "Windows Build"
      os: windows
      before_install:
        - choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System'
      script:
        - cmake -S . -B build
        - cmake --build build --config Release

notifications:
  email: false

